clusters:
  - name: alpha
    machineType: n1-highmem-2
    bootDiskSizeGb: 100
    zone: us-central1-a
    hubs:
    - name: a

fileservers:
  - name: 1
    machineType: n1-highcpu-8
    dataDiskSizeGb: 1000
    zone: us-central1-a

project: data8x-scratch
admins:
  - YuviPanda@gmail.com
