hubs:
  - name: e
    zone: us-central1-b
    k8s:
      machineType: n1-standard-2
      bootDiskSizeGb: 1000
    nfs:
      machineType: n1-standard-4
      dataDiskSizeGb: 1000

project: data8x-scratch
