region: us-central1

outerEdge:
  machineType: n1-standard-2
  bootDiskSizeGb: 100
  initialNodeCount: 1
  zone: us-central1-a
  proxy:
    replicaCount: 1

clusters:
  cluster-alpha:
    machineType: n1-standard-4
    bootDiskSizeGb: 100
    initialNodeCount: 5
    zone: us-central1-a
    hubs:
      hub-a: {}
      hub-b: {}
  cluster-beta:
    machineType: n1-standard-4
    bootDiskSizeGb: 100
    initialNodeCount: 5
    zone: us-central1-a
    hubs:
      hub-y: {}
      hub-z: {}


fileservers:
  fileserver-01:
    machineType: n1-highcpu-2
    dataDiskSizeGb: 1000
    zone: us-central1-a
  fileserver-02:
    machineType: n1-highcpu-2
    dataDiskSizeGb: 1000
    zone: us-central1-a

project: data8x-scratch
admins:
  - YuviPanda@gmail.com
