clusters:
  - name: alpha
    machineType: n1-standard-2
    bootDiskSizeGb: 1000
    zone: us-central1-b
    hubs:
    - name: g
      nfs:
        machineType: n1-highcpu-32
        dataDiskSizeGb: 4000

project: data8x-scratch
