clusters:
  alpha:
    machineType: n1-highmem-2
    bootDiskSizeGb: 100
    initialNodeCount: 2
    zone: us-central1-a
    hubs:
      hub-a: {}


fileservers:
  "1":
    machineType: n1-highcpu-8
    dataDiskSizeGb: 1000
    zone: us-central1-a

project: data8x-scratch
admins:
  - YuviPanda@gmail.com
