prometheus:
  networkPolicy:
    enabled: true
  nodeExporter:
    updateStrategy:
      type: RollingUpdate
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  rbac:
    create: true
    persistentVolume:
      storageClass: ssd
