apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inner-edge-proxy
  labels:
    app: inner-edge
    component: proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  template:
    metadata:
      annotations:
        # This lets us autorestart when the configmap changes!
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: inner-edge
        component: proxy
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      volumes:
      - configMap:
          name: inner-edge-proxy-config
        name: inner-edge-proxy-config
      containers:
        - name: {{ .Chart.Name }}
          image: openresty/openresty:1.13.6.1-1-xenial
          ports:
            - containerPort: 80
          volumeMounts:
          - name: inner-edge-proxy-config
            mountPath: /etc/nginx/conf.d
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}