kind: Secret
apiVersion: v1
metadata:
  name: csql-secret
type: Opaque
data:
  credentials.json: {{ .Values.csql.serviceAccountKey | b64enc | quote }}
  username: {{ .Values.csql.proxy.username | b64enc | quote }}
  password: {{ .Values.csql.proxy.password | b64enc | quote }}