apiVersion: v1
kind: Service
metadata:
  name: edge-proxy
  labels:
    app: edge
    component: proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  {{ if .Values.proxy.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.loadBalancerIP }}
  {{ end }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    {{ if .Values.tls.enabled }}
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    {{ end }}
  selector:
    app: edge
    component: proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
