apiVersion: v1
kind: Service
metadata:
  name: reposync
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: reposync
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: reposync
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9418
      targetPort: 9418
