jupyterhub:
  proxy:
    networkPolicy:
      enabled: true
    service:
      type: ClusterIP
    chp:
      resources:
        requests:
          cpu: 0.4
          memory: 512Mi
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  hub:
    networkPolicy:
      enabled: true
    concurrentSpawnLimit: 100
    resources:
      requests:
        cpu: 1
        memory: 1Gi
    extraVolumes:
    - name: csql-secret
      secret:
        secretName: csql-secret
    extraContainers:
    - name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.11
      command:
      - "/cloud_sql_proxy"
      - "-instances={{config.project}}:{{config.region}}:{{ deployment }}-nfs-db-instance=tcp:5432"
      - "-credential_file=/secrets/cloudsql/credentials.json"
      volumeMounts:
        - name: csql-secret
          mountPath: /secrets/cloudsql
          readOnly: true
    extraEnv:
      HUB_NAME: {{ name }}
      CLUSTER_NAME: {{ cluster_name }}
      SHARDER_DB_USERNAME: {{ deployment }}-db-proxyuser
      SHARDER_DB_PASSWORD: {{ config.sql.password }}
      SHARDER_DB_NAME: {{ deployment }}-nfs-sharder-db
    extraConfig: |
      {{ files['sharder.py']|indent(6) }}

      {{ files['sharding-config.py']|indent(6) }}

      {{ files['hub-marker.py']|indent(6) }}

    extraConfigMap:
      deployment: {{ deployment|safe }}
      full-config: {{ config|jsonify|safe }}

  singleuser:
    networkPolicy:
      enabled: true
      egress:
      - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      - to:
        - podSelector:
            matchLabels:
              app: reposync
    memory:
      limit: 128M
      guarantee: 128M
    image:
      name: gcr.io/data8x-scratch/user-image
      tag: v2
    storage:
      type: custom
