jupyterhub:
  hub:
    concurrentSpawnLimit: 100
    extraEnv:
      HUB_NAME: {{ name }}
    extraConfig: |
      {{ files['sharder.py']|indent(6) }}

      {{ files['sharding-config.py']|indent(6) }}

      {{ files['hub-marker.py']|indent(6) }}

    extraConfigMap:
      deployment: {{ deployment|safe }}
      full-config: {{ config|jsonify|safe }}

  singleuser:
    schedulerStrategy: pack
    image:
      name: yuvipanda/data8x-user
      tag: v2
    storage:
      type: custom