jupyterhub:
  hub:
    concurrentSpawnLimit: 100
    extraConfig: |
      {{ files['sharder.py']|indent(6) }}

      {{ files['sharding-config.py']|indent(6) }}

    extraConfigMap:
      deployment: {{ deployment|safe }}
      full-config: {{ config|jsonify|safe }}

  singleuser:
    schedulerStrategy: pack
    image:
      name: yuvipanda/data8x-user
      tag: v2
    storage:
      type: custom

  proxy:
    secretToken: {{ hub.proxySecret }}