dependencies:
- name: jupyterhub
  version: "v0.7-4c3879e"
  repository: https://jupyterhub.github.io/helm-chart/
  #version: "v0.7-19ed610"
  #repository: "file:///home/yuvipanda/code/zero-to-jupyterhub-k8s/jupyterhub"
