region: us-central1

miscCluster:
  machineType: n1-standard-4
  bootDiskSizeGb: 100
  initialNodeCount: 2
  zone: us-central1-a
  outerEdge:
    proxy:
      loadBalancerIP: 104.197.5.28
      replicaCount: 3
    sharder:
      replicaCount: 3
  hwuploader:
    replicaCount: 3
    fileserver: fileserver-01

externalTraffic:
  allowedHosts:
  - img.youtube.com
  - www.inferentialthinking.com

clusters:
  cluster-alpha:
    machineType: n1-highmem-16
    bootDiskSizeGb: 100
    initialNodeCount: 2
    zone: us-central1-a
    hubs:
      hub-alpha-01: {}
      hub-alpha-02: {}
      hub-alpha-03: {}
      hub-alpha-04: {}
      hub-alpha-05: {}
      hub-alpha-06: {}
      hub-alpha-07: {}
      hub-alpha-08: {}
      hub-alpha-09: {}
      hub-alpha-10: {}

  cluster-beta:
    machineType: n1-highmem-16
    bootDiskSizeGb: 100
    initialNodeCount: 2
    zone: us-central1-a
    hubs:
      hub-beta-01: {}
      hub-beta-02: {}
      hub-beta-03: {}
      hub-beta-04: {}
      hub-beta-05: {}
      hub-beta-06: {}
      hub-beta-07: {}
      hub-beta-08: {}
      hub-beta-09: {}
      hub-beta-10: {}

fileservers:
  fileserver-01:
    machineType: n1-highcpu-8
    dataDiskSizeGb: 1000
    zone: us-central1-a
  fileserver-02:
    machineType: n1-highcpu-8
    dataDiskSizeGb: 1000
    zone: us-central1-a

project: data8x-scratch
admins:
  - YuviPanda@gmail.com
